name: Send to Qiita

on:
  push:
    branches: [cicd_sample]

jobs:
  send-to-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git branch -a
      - run: echo "ğŸ This job's status is ${{ job.status }}."
