name: Send to Qiita

on:
  push:
    branches: [cicd_sample]

jobs:
  send-to-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          for file in $(git diff ${{github.event.before}}..${{github.event.after}} --name-only --diff-filter=A -- '*.md') ; do
            echo $(file)
          done
      - run: echo "ğŸ This job's status is ${{ job.status }}."
