name: Send to Qiita

on:
  push:
    branches: [cicd_sample]

jobs:
  send-to-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "2"
      - run: |
          for changedFile in $(git diff ${{github.event.before}}..${{github.event.after}} --name-only) ; do
            echo $changedFile
          done
      - run: echo "before hash ${{github.event.before}}"
      - run: echo "after hash ${{github.event.after}}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
