name: Send to Qiita

on:
  push:
    branches: [cicd_sample]

jobs:
  send-to-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - run: git log
      - run: echo "before hash ${{github.event.before}}"
      - run: echo "after hash ${{github.event.after}}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
